replicaCount: 1

image:
  repository: ghcr.io/chazapp/solfej
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  name: solfej
  type: ClusterIP
  port: 80

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  enabled: true
  host: solfej.chaz.pro 
  tls:
    secretName: solfej-tls
    hosts:
      - solfej.chaz.pro